---
title: "메뉴바(navbar:)"
categories: [웹사이트, 네비게이션, 상부메뉴]
---

페이지 상부 메뉴 설정

### 프로젝트 설정(_quarto.yml)

```yml
website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
```

### 메뉴바(navbar:) 옵션

- `title: ` Navbar title (uses the site: title if none is specified). Use title: false to suppress the display of the title on the navbar.
- `logo: ` Logo image to be displayed left of the title. When using a _brand.yml with a logo, the brand logo is automatically displayed. Use logo: false to suppress the brand logo on the navbar.
- `logo-alt: ` Alternate text for the logo image.
- `logo-href: ` Target href from navbar logo / title. By default, the logo and title link to the root page of the site (`/index.html`).
- `background: ` Background color (“primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or hex color).
- `foreground: ` Foreground color (“primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or hex color). The foreground color will be used to color navigation elements, text and links that appear in the navbar.
- `search: ` Include a search box (true or false).
- `tools: ` List of ***navbar tools*** (e.g., link to github or bluesky, etc.). See Navbar Tools for details.
- `left: `, `right: ` Lists of ***navigation items*** for left and right side of navbar.
- `pinned: ` Always show the navbar (true or false). Defaults to false, and uses headroom.js to automatically show the navbar when the user scrolls up on the page.
- `collapse: ` Collapse the navbar items into a hamburger menu when the display gets narrow (defaults to true).
- `collapse-below: ` Responsive breakpoint at which to collapse navbar items to a hamburger menu (“sm”, “md”, “lg”, “xl”, or “xxl”, defaults to “lg”).
- `toggle-position: ` The position of the collapsed navbar hamburger menu when in responsive mode (“left” or “right”, defaults to “left”).
- `tools-collapse: ` Collapse tools into the navbar menu when the display becomes narrow.

#### 메뉴바 네니베이션 항목(navigation items) 리스트

- `href: ` Link to file contained with the project or external URL.
- `text: ` Text to display for navigation item (defaults to the document title if not provided).
- `icon: ` Name of one of the standard Bootstrap 5 icons (e.g., “github”, “bluesky”, “share”, etc.).
- `aria-label: ` Accessible label for the navigation item.
- `rel: ` Value for rel attribute. Multiple space-separated values are permitted.
- `target: ` Value for target attribute. E.g., _blank to open in a new tab.
- `menu: ` List of navigation items to populate a drop-down menu.

#### 메뉴바 툴(tools:) 리스트

아이콘 이름(Bootstrap icons), 링크로 구성되며 메뉴바 오른쪽에 표시된다.

```yml
website:
  navbar:
    tools:
      - icon: bluesky
        href: https://bsky.app
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
```
