---
title: "사이드바(sidebar:)"
categories: [웹사이트, 네비게이션, 왼쪽메뉴]
---

페이지 왼쪽 메뉴 설정

### 프로젝트 설정(_quarto.yml)

```yml
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Basics"
        href: basics-summary.qmd
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        ...
      - acknowledgment.qmd
```

### 사이드바(sidebar:) 옵션

- `id: ` Optional identifier (used only for hybrid navigation, described below).
- `title: ` Sidebar title (uses the project title if none is specified).
- `logo: ` Optional logo image. When using a _brand.yml with a logo, the brand logo is automatically displayed. Use logo: false to suppress the brand logo on the sidebar.
- `logo-alt: ` Alternate text for the logo image.
- `logo-href: ` Target href from sidebar logo. By default, the logo and title link to the root page of the site (`/index.html`).
- `search: ` Include a search box (true or false). Note that if there is already a search box on the top navigation bar it won’t be displayed on the sidebar.
- `tools: ` List of ***sidebar tools*** (e.g., link to github or bluesky, etc.). See the next section for details.
- `contents: ` List of ***navigation items*** to display (typically top level items will in turn have a list of sub-items).
- `style: ` “docked” or “floating”.
- `type: ` “dark” or “light” (hint to make sure the text color is the inverse of the background).
- `background: ` Background color (“none”, “primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or “white”). Defaults to “light”.
- `foreground: ` Foreground color (“primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or hex color). The foreground color will be used to color navigation elements, text and links that appear in the sidebar.
- `border: ` Whether to show a border on the sidebar. “true” or “false”.
- `alignment: ` Alignment (“left”, “right”, or “center”).
- `collapse-level: ` Whether to show sidebar navigation collapsed by default. The default is 2, which shows the top and next level fully expanded (but leaves the 3rd and subsequent levels collapsed).
- `pinned: ` Always show a title bar that expands to show the sidebar at narrower screen widths (true or false). Defaults to false, and uses headroom.js to automatically show the navigation bar when the user scrolls up on the page.

::: {.callout-important}
### 모든 페이지에 표시
옵션`id:`나 `title:`을 지정하지 않은 항목(sidebar items)은 웹사이트 모든 페이지에 표시된다.
### 일부 페이지에 표시
옵션`id:`나 `title:`을 지정한 항목(sidebar items)은 사이드바 `contents:` 리스트에 포함된 페이지들이나, 사이드바 `id:`를 지정한 폴더(`_metadata.yml`에서 지정), 페이지(`yml` 헤더에서 지정)에 표시된다. 
:::

#### 항목 자동 생성

파일시스템에서 사이드바 항목을 자동으로 생성하는 설정

##### 자동항목 생성 규칙

- 항목 이름은 문서의 `title:` 필드에서 읽어온다.
- 하부 폴더는 폴더 이름을 사용해 섹션(sections)을 형성한다. 폴더 이름에 포함된 `-`, `_`는 섹션 이름에서 빈칸으로 바뀌고, 첫글자가 3.대문자로 바뀐다. 폴더에 `title:` 필드를 갖는 `index.qmd` 파일을 형성하면 폴더 이름 대신 지정된 이름으로 섹션이름을 설정한다. 
- 항목 순서는 파일이름 순으로 정렬된다. (문서 `yml` 해더에 `order:` 필드를 지정하면 바꿀 수 있음)

##### 자동생성 항목 지정

항목 지동생성은 프로젝트 폴더 내의 모든 파일을 대상으로 한다. 이 기본값과 다르게 항목을 생성하려면 폴더 이름을 지정하거나 glob 패턴을 사용한다.

- 프로젝트 폴더의 모든 파일(기본값)

```yml
website:
  sidebar:
    contents: auto
```

- 프로젝트 `/`폴더 안의 파일로 제한

```yml
website:
  sidebar:
    contents: /*
```

- glob 패턴 사용

```yml
sidebar:
  contents: reports

sidebar:
  contents: reports/*
  
sidebar:
  contents: "*.ipynb"
```

::: {.callout-important}
### YAML에서 `*`로 시작하는 패턴
YAML에서 `*`로 시작하는 패턴을 사용할 때 반드시 `" "`를 사용해야 한다.
:::

- `sidebar:` 안에서 `contents:`의 위계

```yml
website:
  sidebar:
    contents:
      - about.qmd
      - contributing.qmd
      - section: Reports
        contents: reports
```

- 일반 항목과 auto:의 사용

```yml
website:
  sidebar:
    contents:
      - about.qmd
      - contributing.qmd
      - auto: "*-report.qmd"
```

#### 사이드바 툴(tools:) 리스트

아이콘 이름(Bootstrap icons), 링크로 구성되며 사이드바 상단에 표시된다.

```yml
website:
  sidebar:
    tools:
      - icon: bluesky
        href: https://bsky.app
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
```
