project:
  type: website

language: korean.yml

website:
  title: "wintree"
  navbar:
    logo: "logo.png"
    right:
      - href: index.qmd
        text: "Home"
      - href: data.qmd
        text: "Data"
      - href: about.qmd
        text: "About"
  sidebar: 
    - id: home
      title: "Home"
      contents: 
      - index.qmd
      - data.qmd
      - text: "---"
    - id: data
      title: "Data"
      contents: 
      - index.qmd
      - data.qmd
      - text: "---"
      - auto: FILES
listing: 
    sort: "date desc"
    sort-ui: true
    filter-ui: true
    categories: true
    date-format: iso

format:
  html:
    theme: spacelab
    css: styles.css
