project:
  type: website

website:
  title: "wintree"
  navbar:
    logo: "logo.png"
    right:
      - href: index.qmd
        text: "Home"
      - href: data.qmd
        text: "Data"
#      - href: quarto.qmd
#        text: "Quarto"
      - href: about.qmd
        text: "About"
  sidebar:
    - id: menu
      title: "Menu"
      collapse-level: 3
      contents:
        - text: "Top Menu"
        - text: "---" 
        - index.qmd
        - data.qmd
#        - quarto.qmd
        - text: "---" 
    - id: data
      title: "Data"
      contents: 
        - text: "Top Menu"
        - text: "---" 
        - index.qmd
        - data.qmd
#        - quarto.qmd
        - text: "---"
        - auto: FILES
#    - id: quarto
#      title: "Quarto"
#      contents: 
#        - text: "Top Menu"
#        - text: "---" 
#        - index.qmd
#        - data.qmd
#        - quarto.qmd
#        - text: "---"
#        - auto: QUARTO

format:
  html:
    theme: spacelab
    css: styles.css

language: korean.yml
date-format: iso
toc: true
