---
title: "티블 개요"
date: "2026-04-15"
date-modified: "2026-04-15"
categories: [tibble, tbl_df, tidyverse]
toc: true
draft: false
---

데이터 프레임의 현대적 재해석 `tibble`, `tbl_df`

#### 티블 설치

```{r}
#| label: install-tibble
#| eval: false
#| output: false
# 패키지 모음 tidyverse의 구성 요소로서 설치
install.packages("tidyverse")
# 티블 패키지만 단독으로 설치
install.packages("tibble")
# 깃헙에서 개발자 버전 설치
pak::pak("tidyverse/tibble")
```

#### 티블 객체 생성

##### 데이터프레임을 `as_tibble()`로 변환

```{r}
#| label: as-tibble
#| collapse: true
library(tibble)
head(datasets::women, 3)
head(as_tibble(women), 3)
```

##### 열벡터에 `tibble()` 사용

```{r}
#| label: tibble
#| collapse: true
tibble(x = 2:4, y = 7, z = x^2 + y)
```


::: {.callout-important}

#### tibble()

- 입력 값의 형식을 변경없이 그대로(예, 리스트 형식의 열) 사용한다.
- 압력 값의 재사용 규칙은 길이가 1인 경우에만 적용된다.
- 변수 이름을 변경하지 않는다. (row_names()도 만들지 않음)

:::

##### 행별 입력값에 `tribble()` 사용 

```{r}
#| label: tribble
#| collapse: true
tribble(
    ~코드, ~시군구, ~영문,
    "11", "서울특별시", "Seoul",
    "11110", "종로구", "Jongno-gu",
    "11140", "중구", "Jung-gu"
)
```
