---
title: "분류 피드"
categories: [웹사이트, 리스팅, 범주, 분류]
---

리스팅 분류(Categpries) 및 피드(Feeds)

### 분류(Categories)

#### 지정

```yml
---
listing:
  categories: true
---
```

#### 스타일 옵션

- `numbered`	Displays a list of categories in alphabetical order with the number of items in that category displayed next to the category name.
- `unnumbered`	Display a list of categories in alphabetical order.
- `cloud`	Displays a ‘word cloud’ of categories.

### 피드(Feeds)

#### 설정

```yml
---
listing:
  contents: posts
  feed: true
---
```

```yml
# _quarto.yml
website:
  site-url: "https://www.quarto.org"
```

#### 피드 옵션

`items`	The number of items to include in your feed. Defaults to 20.
`type`	full, partial or metadata. full, the default, includes the full contents of each document in the feed. partial includes the description, if available, otherwise the first paragraph in the feed. metadata includes only the title, description, and other document metadata in the feed.
`title`	The title for this feed. Defaults to the site title provided in your _quarto.yml file.
`image`	The image for this feed. If not specified, the image for the page the listing appears on will be used, otherwise an image will be used if specified for the site in your _quarto.yml file.
`description`	The description of this feed. If not specified, the description for the page the listing appears on will be used, otherwise the description of the site will be used if specified in your _quarto.yml file.
`language`	The language of the feed. Omitted if not specified. See https://www.rssboard.org/rss-language-codes for a list of valid language codes.
`categories`	Generates a separate feed for each of the categories included in this list of category names.
