---
title: "리스팅 필드"
categories: [웹사이트, 리스팅, 필드명]
---

quarto는 리스트의 필드를 문서 프론트메터의 메타데이터에서 읽어들인다.

### 필드 이름

`title`	The title of the item, read from the title field of the front matter (or the first H1 of the document).
`subtitle`	The subtitle of the item, read from the subtitle field of the front matter.
`author`	The author of the item, read from the author field of the front matter.
`description`	The description of the item, read from the description or abstract field of the front matter or from the first paragraph of the document.
`date`	The date of the item, read from the date field of the front matter.
`image`	The image for this item, read from the image field of the front matter, or automatically discovered by taking the first of an image of class preview-image, an image with a file name starting with feature, cover, or thumbnail, or the first image to appear in the document.
`image-alt`	The alt text for the image for this item.
`word-count`	A word count for this item.
`reading-time`	An estimate of the reading time for this item, computed by counting the words in the item and assuming a reading speed of 200 words per minute.
`categories`	Categories for the item, read from the categories field of the front matter.
`filename`	The name of the input file.
`file-modified`	The last modified date of this input file.

### 리스팅 타입별 필드 표기

- `default`: `title`, `subtitle`, `author`, `description`, `date`, `image`
- `table`: `title`, `author`, `date`
- `grid`: `title`, `author`, `description`, `date`, `image`

### 필드 표시 사용자화

#### `fields:` 옵션으로 지정

```yml
---
listing:
  type: table
  contents: posts
  fields: [image, date, title, author, reading-time]
---
```

