---
title: "건설공사계약금액"
date: "2026-04-15"
date-modified: "2026-04-15"
categories: [건설공사, 계약금액]
toc: true
draft: false
---

2025년 현장 소재지별 건설공사 계약금액 (분기)

#### 건설공사계약

```{r}
#| echo: false
#| output: false
library(tidyverse)
```

[데이터 파일: 현장소재지별_건설공사계약금액.csv](../FILES/%ED%86%B5%EA%B3%84%EB%88%84%EB%A6%AC/%EA%B1%B4%EC%84%A4/%ED%98%84%EC%9E%A5%EC%86%8C%EC%9E%AC%EC%A7%80%EB%B3%84_%EA%B1%B4%EC%84%A4%EA%B3%B5%EC%82%AC%EA%B3%84%EC%95%BD%EA%B8%88%EC%95%A1.csv){download=""}

```{r}
#| echo: false
#| output: false
cont <- read_csv("FILES/통계누리/건설/현장소재지별_건설공사계약금액.csv") |>
    mutate(권역별 = case_when(시도별 == "전국" ~ "전국", 시도별 == "서울" ~ "수도권", 시도별 == "부산" ~ "영남권", 시도별 == "대구" ~ "영남권", 시도별 == "인천" ~ "수도권", 시도별 == "광주" ~ "호남권", 시도별 == "대전" ~ "충청권", 시도별 == "울산" ~ "영남권", 시도별 == "세종" ~ "충청권", 시도별 == "경기" ~ "수도권", 시도별 == "강원" ~ "강원권", 시도별 == "충북" ~ "충청권", 시도별 == "충남" ~ "충청권", 시도별 == "전북" ~ "호남권", 시도별 == "전남" ~ "호남권", 시도별 == "경북" ~ "영남권", 시도별 == "경남" ~ "영남권", 시도별 == "제주" ~ "영남권"))
met <- cont |> summarise(`계약금액(억원)` = sum(`계약금액(억원)`), .by = c(분기, 구분))
ccd <- cont |> summarise(`계약금액(억원)` = sum(`계약금액(억원)`), .by = c(분기, 시도별))
con <- cont |> summarise(`계약금액(억원)` = sum(`계약금액(억원)`), .by = c(분기, 권역별))
```

\

##### 2025년 현장 소재지별 건설공사 계약금액(억원)

```{r}
#| echo: false
#| tab.cap: 권역별 건설공사 계약금액(억원)
knitr::kable(con |> filter(as.numeric(substr(`분기`, 1, 4)) == 2025) |> pivot_wider(names_from = `분기`, values_from = `계약금액(억원)`) |> rowwise() |> mutate(`2025` = sum(c_across(`2025/01`:`2025/04`))), format.args = list(big.mark = ",", scientific = FALSE))
```

```{r}
#| echo: false
#| tab.cap: 시도별 건설공사 계약금액(억원)
knitr::kable(ccd |> filter(as.numeric(substr(`분기`, 1, 4)) == 2025) |> pivot_wider(names_from = `분기`, values_from = `계약금액(억원)`) |> rowwise() |> mutate(`2025` = sum(c_across(`2025/01`:`2025/04`))), format.args = list(big.mark = ",", scientific = FALSE))
```

\

##### 2025년 4분기 현장 소재지별 건설공사 계약금액(억원)

```{r}
#| echo: false
#| output: false
con4q <- con |> filter(`분기` == "2025/04" | `분기` == "2025/03" | `분기` == "2024/04") |> pivot_wider(names_from = `분기`, values_from = `계약금액(억원)`) |> mutate(YoY = sprintf("%.2f%%", 100 * (`2025/04` - `2024/04`) / `2024/04`), QoQ = sprintf("%.2f%%", 100 * (`2025/04` - `2025/03`) / `2025/03`))
```

```{r}
#| echo: false
#| tab.cap: 2025년 4분기 권역별 전년동기, 전기대비 건설공사 계약금액(억원)
knitr::kable(con4q, align = "lrrrrr", format.args = list(big.mark = ","))
```

\

```{r}
#| echo: false
#| output: false
theme_set(theme_bw(base_family="Apple SD 산돌고딕 Neo"))
#theme(text=element_text(family="Apple SD 산돌고딕 Neo"))
gd <- con |> slice(260:264, 278:282, 284:288) |> mutate(권역별 = factor(권역별, levels = c("수도권", "영남권", "충청권", "호남권", "강원권")))
```

```{r}
#| echo: false
ggplot(gd, aes(x = 분기, y = `계약금액(억원)`, fill = 권역별)) +
    geom_bar(position = "dodge", stat = "identity") +
    ggtitle("2025년 4분기 권역별 건설공사 계약금액 (전년동기대비, 전기대비 )") +
    scale_fill_brewer(palette = "Purples")
```


```{r}
#| echo: false
#| output: false
ccd4q <- ccd |> filter(`분기` == "2025/04" | `분기` == "2025/03" | `분기` == "2024/04") |> pivot_wider(names_from = `분기`, values_from = `계약금액(억원)`) |> mutate(YoY = sprintf("%.2f%%", 100 * (`2025/04` - `2024/04`) / `2024/04`), QoQ = sprintf("%.2f%%", 100 * (`2025/04` - `2025/03`) / `2025/03`))
```

```{r}
#| echo: false
#| tab.cap: 2025년 4분기 시도별 전년동기, 전기대비 건설공사 계약금액(억원)
knitr::kable(ccd4q, align = "lrrrrr", format.args = list(big.mark = ","))
```

\

```{r}
#| echo: false
#| output: false
theme_set(theme_bw(base_family="Apple SD 산돌고딕 Neo"))
gd <- cont |> filter(권역별 == "수도권") |>
    filter(`분기` == "2025/04" | `분기` == "2025/03" | `분기` == "2024/04") |>
    summarise(`계약금액(억원)` = sum(`계약금액(억원)`), .by = c(분기, 시도별)) |>
    mutate(시도별 = factor(시도별, levels = c("경기", "서울", "인천")))
# 빈 데이터 삽입
```

```{r}
#| echo: false
ggplot(gd, aes(x = 분기, y = `계약금액(억원)`, fill = 시도별)) +
    geom_bar(position = "dodge", stat = "identity") +
    ggtitle("2025년 4분기 수도권 건설공사 계약금액 (전년동기대비, 전기대비 )") +
    scale_fill_brewer(palette = "Purples")
```

```{r}
#| echo: false
#| output: false
theme_set(theme_bw(base_family="Apple SD 산돌고딕 Neo"))
gd <- cont |> filter(권역별 == "충청권") |>
    filter(`분기` == "2025/04" | `분기` == "2025/03" | `분기` == "2024/04") |>
    summarise(`계약금액(억원)` = sum(`계약금액(억원)`), .by = c(분기, 시도별)) |>
    mutate(시도별 = factor(시도별, levels = c("충남", "충북", "대전", "세종")))
```

```{r}
#| echo: false
ggplot(gd, aes(x = 분기, y = `계약금액(억원)`, fill = 시도별)) +
    geom_bar(position = "dodge", stat = "identity") +
    ggtitle("2025년 4분기 충청권 건설공사 계약금액 (전년동기대비, 전기대비 )") +
    scale_fill_brewer(palette = "Purples")
```
