---
title: "메뉴목록(sidebar)"
date: "2026-04-12"
date-modified: "2026-04-15"
categories: [quarto, website, sidebar]
toc: true
---

웹 페이지 좌측 메뉴목록 설정

#### 프로젝트 설정(_quarto.yml)

```yml
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Basics"
        href: basics-summary.qmd
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        ...
      - acknowledgment.qmd
```

#### 사이드바(sidebar) 옵션

- `id` 지정자(이름, 메뉴바와 사이드메뉴의 결합에 사용).
- `title` 제목 (지정하지 않으면 프로젝트 제목 사용).
- `logo` 로고 이미지(옵션). 로고가 있는 `_brand.yml`을 사용하면 로고가 자동으로 표시됨(브랜드 로고를 사용하지 않게 하려면 `logo: false` 지정).
- `logo-alt` 로고 이미지르 대신할 텍스트.
- `logo-href` 사이드바 로고의 타깃 주소(`href`). 로고와 타이틀의 링크 기본값은 사이트의 루트 페이지(`/index.html`).
- `search` 탐색 박스를 표시할 지 여부(true 또는 false). 메뉴바에 탐색 박스가 표시되는 것으로 설정되어 있으면 사이드바에는 나타나지 않는다.
- `tools` 사이드바 툴의 리스트(`github` 이나 `bluesky` 연결 등).
- `contents` 네비게이션 항목(navigation items) 리스트. 상위 레벨의 항목들은 하위 레벨 항목에도 리스트 된다.
- `style` “docked” 또는 “floating”.
- `type` “dark” 또는 “light” (텍스트 색상을 배경색의 반대색으로).
- `background` 배경색 (“none”, “primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or “white”). 기본값 “light”.
- `foreground` 전경색 (“primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or hex color). 전경색은 사이드바에 표시되는 네비게이션 항목, 텍스트와 링크에 사용된다.
- `border` 사이드바 가장자리를 표시할지 여부. “true” 또는 “false”.
- `alignment` 정렬 (“left”, “right”, 또는 “center”).
- `collapse-level` 사이드바가 보일 때 자동으로 펼처질 단계. 기본값은 2.
- `pinned` 화면 폭이 좁을 때 사이드바를 펼쳐 주는 타이틀바를 항상 보여줄지 여부("true" 또는 "false"). 기본값은 "false" 이고 사용자가 화면을 위로 스크롤 했을 때 네비게이션 바를 자동으로 보여주는  `headroom.js`를 사용한다.

::: {.callout-important}
### 모든 페이지에 표시
옵션`id:`나 `title:`을 지정하지 않은 항목(sidebar items)은 웹사이트 모든 페이지에 표시된다.
### 일부 페이지에 표시
옵션`id:`나 `title:`을 지정한 항목(sidebar items)은 사이드바 `contents:` 리스트에 포함된 페이지들이나, 사이드바 `id:`를 지정한 폴더(`_metadata.yml`에서 지정), 페이지(`yml` 헤더에서 지정)에 표시된다. 
:::

#### 항목 자동 생성

파일시스템에서 사이드바 항목을 자동으로 생성하는 설정

##### 자동항목 생성 규칙

- 항목 이름은 문서의 `title:` 필드에서 읽어온다.
- 하부 폴더는 폴더 이름을 사용해 섹션(sections)을 형성한다. 폴더 이름에 포함된 `-`, `_`는 섹션 이름에서 빈칸으로 바뀌고, 첫글자가 3.대문자로 바뀐다. 폴더에 `title:` 필드를 갖는 `index.qmd` 파일을 형성하면 폴더 이름 대신 지정된 이름으로 섹션이름을 설정한다. 
- 항목 순서는 파일이름 순으로 정렬된다. (문서 `yml` 해더에 `order:` 필드를 지정하면 바꿀 수 있음)

##### 자동생성 항목 지정

항목 지동생성은 프로젝트 폴더 내의 모든 파일을 대상으로 한다. 이 기본값과 다르게 항목을 생성하려면 폴더 이름을 지정하거나 glob 패턴을 사용한다.

- 프로젝트 폴더의 모든 파일(기본값)

```yml
website:
  sidebar:
    contents: auto
```

- 프로젝트 `/`폴더 안의 파일로 제한

```yml
website:
  sidebar:
    contents: /*
```

- glob 패턴 사용

```yml
sidebar:
  contents: reports

sidebar:
  contents: reports/*
  
sidebar:
  contents: "*.ipynb"
```

::: {.callout-important}
### YAML에서 `*`로 시작하는 패턴
YAML에서 `*`로 시작하는 패턴을 사용할 때 반드시 `" "`를 사용해야 한다.
:::

- `sidebar:` 안에서 `contents:`의 위계

```yml
website:
  sidebar:
    contents:
      - about.qmd
      - contributing.qmd
      - section: Reports
        contents: reports
```

- 일반 항목과 auto:의 사용

```yml
website:
  sidebar:
    contents:
      - about.qmd
      - contributing.qmd
      - auto: "*-report.qmd"
```

#### 사이드바 툴(tools) 리스트

아이콘 이름(Bootstrap icons), 링크로 구성되며 사이드바 상단에 표시된다.

```yml
website:
  sidebar:
    tools:
      - icon: bluesky
        href: https://bsky.app
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
```

#### 사이드바 감추기

```yml
---
# Hides the sidebar on this page
sidebar: false
---
```
